export const FETCH_BOOKDATA = "FETCH_BOOKDATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const FETCH_AUTHORDATA = "FETCH_AUTHORDATA"
export const FETCH_CATEGORYDATA = "FETCH_CATEGORYDATA"
export const ADD_BOOK = "ADD_BOOK"
export const FETCH_USERDATA = "FETCH_USERDATA"